name: Organization PR Quality Check

on:
  workflow_call:

jobs:
  # ENFORCE that all the checkboxes in a PR first message are ticked
  check-checklist:
    name: "Check PR Checklist Completion"
    runs-on: ubuntu-latest
    steps:
      - name: Verify checklist is complete
        uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
